spring:
  jpa:
    database: DEFAULT
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mariadb://10.0.1.1:3306/tylerrobbins
    username: tyler
    password: quintrix-tyler
nickNameApiUri: http://api.friendlyrobot.fr/v2/nicknames/{name}/email/tylerrobbins5678@gmail.com/company/quintrix

logging:
  level:
    org.springframework: ERROR
    us.tylerrobbins: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log
